label prologue:
    "Ugh... hu..."
    "I messed up my exam."
    "But they said they got over 90 on average."
    "We watched a movie together yesterday..."
    "But I was the only one who failed."
    "Only me."

    inha "Don't cry..."
    inha "Wait a second, my mom's calling me."
    inha "Hello? Uh.. Dinner tonight?"
    inha "I don't think I can."
    inha "I have art academy today..."
    mom "Ye-Jun's mom moved to the neighborhood, and she suggested we have dinner together~"
    mom "Oh, do you still remember Ye-jun by the way?"
    thought "Ye-Jun...?"
    yejun "In-Ha, You're really amazing!"
    yejun "I want to be just like you..."
    thought "Ah, the one who used to live next door to us when I was in Elementary School...!"
    mom "Well... it happened when you were a kid, didn't it?"
    mom "Since he lived net door, you two were like two peas in a pod!"
    inha "Uh, yeah..."
    mom "Anyways, his mom's going to come after dinner."
    mom "So eat on your home and then come home~"
    minji "Hey, let's go~"
    inha "Yeah, Minji."
    inha "What's the matter with Si-Hyeon?"
    minji "They said she messed up the test, that's all."
    minji "I heard that after she got a boyfriend, she skipped a lot of academy classes."
    minji "It's absolutely insane."
    minji "How can you even think about dating a 3rd-year High School student."
    inha "Yeah, totally."
    inha "Every minute down to every second is important right now."
    minji "Ah! By the way, I didn't do the homework for the academy."
    inha "If you skip homework now, won't you have to do twice as much later?"
    