image school_exterior = "images/bg_school_exterior.webp"
image school_rooftop = "images/bg_school_rooftop.avif"
image crosswalk = "images/bg_crosswalk.webp"
image classroom = "images/bg_classroom.avif"
image academy_night = "images/bg_academy_night.jpg"
image rooftop = "images/bg_rooftop.jpg"
image rooftop_rain = "images/bg_rooftop_rain.avif"
image exam_hall = "images/bg_exam_hall.jpg"
image room = "images/bg_room.png"
image exhibition = "images/bg_exhibition.webp"

image inn = "images/in.png"
image ip = "images/ip.png"
image iss = "images/is.png"
image isu = "images/isu.png"
image it = "images/it.png"
image js = "images/js.png"